name: verse
description: A dart implementation of distributed version control.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <=4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.2.2
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
